// PWA Service Worker - Generated by it.adi.p Automator
const CACHE_NAME = 'tpa_absensi-cache-v1777169677598';
const ASSETS = ["./","./index.html","./manifest.json"];

self.addEventListener('install', (event) => {
    self.skipWaiting();
    event.waitUntil(
        caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        caches.keys().then((keys) => Promise.all(
            keys.map((k) => {
                if (k !== CACHE_NAME) return caches.delete(k);
            })
        ))
    );
    return self.clients.claim();
});

// Update Strategi Fetching untuk Update Dinamis
self.addEventListener('fetch', (event) => {
    event.respondWith(
        fetch(event.request)
            .then(response => {
                // Update cache secara dinamis bisa ditambahkan di sini
                return response;
            })
            .catch(() => caches.match(event.request))
    );
});